library(forecast)
library(ggplot2)
library(readr)

df <- read_csv('10_years_to_present_get_healthy.csv', skip=2)
summary(df)
head(df)
colnames(df) <- c('month','rel_popularity')
head(df)

x <- ts(df$rel_popularity, frequency = 12)
plot(x)
stl(x, "periodic")
decomposed <- stl(x, s.window="periodic")
plot(decomposed)
